# Generated by Django 3.2.7 on 2021-11-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
