# Generated by Django 3.2.7 on 2021-11-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0003_review_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
